package ua.udunt.hmnd;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.DynamodbEvent;
import com.amazonaws.services.lambda.runtime.events.models.dynamodb.AttributeValue;
import com.amazonaws.services.lambda.runtime.events.models.dynamodb.Identity;
import jakarta.inject.Inject;
import lombok.extern.slf4j.Slf4j;
import ua.udunt.hmnd.model.Message;
import ua.udunt.hmnd.service.SnsService;
import ua.udunt.hmnd.support.MessageBuilder;

import java.util.Map;
import java.util.Optional;

@Slf4j
public class MessageHandler implements RequestHandler<DynamodbEvent, String> {

    @Inject
    SnsService snsService;

    @Override
    public String handleRequest(DynamodbEvent dynamodbEvent, Context context) {
        if (dynamodbEvent == null || dynamodbEvent.getRecords() == null) {
            log.error("Empty DynamoDB event");
            return "NO_RECORDS";
        }
        log.info("Received DynamoDB event: {}", dynamodbEvent);
        for (DynamodbEvent.DynamodbStreamRecord record : dynamodbEvent.getRecords()) {
            String eventName = record.getEventName();
            Map<String, AttributeValue> image = null;
            switch (eventName) {
                case "INSERT", "MODIFY" -> image = record.getDynamodb().getNewImage();
                case "REMOVE" -> {
                    // Check if event generated by TTL expiration
                    String userIdentity = Optional.ofNullable(record.getUserIdentity())
                            .map(Identity::getType)
                            .orElse("");

                    if ("Service".equals(userIdentity)) {
                        image = record.getDynamodb().getOldImage();
                    } else {
                        log.info("Skipping non-TTL event");
                    }
                }
                default -> {
                    log.error("Unsupported event type: {}", eventName);
                    continue;
                }
            }
            if (image == null || image.isEmpty()) {
                log.error("Empty image for event: {}", eventName);
                continue;
            }
            Message message = MessageBuilder.build(image);
            if (!message.isValid()) {
                log.error("Invalid image for event: {}", eventName);
                continue;
            }
            snsService.sendNotification(eventName, message);
        }
        return "OK";
    }

}
